

/****** Object:  View [dbo].[DBColums]    Script Date: 3/17/2025 9:59:55 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

alter VIEW [dbo].[DBColums] AS
SELECT 
    ROW_NUMBER() OVER (ORDER BY c.TABLE_SCHEMA, c.TABLE_NAME, c.ORDINAL_POSITION) AS ROW_NUM, -- Adds row numbers
    c.TABLE_SCHEMA, 
    c.TABLE_NAME, 
    lower(c.COLUMN_NAME) COLUMN_NAME, 
    c.ORDINAL_POSITION, 
    c.IS_NULLABLE, 
    c.DATA_TYPE,
    CASE 
        WHEN kcu.COLUMN_NAME IS NOT NULL THEN CONVERT(bit,1)
        ELSE CONVERT(bit,0)
    END AS IS_PRIMARY_KEY
FROM 
    INFORMATION_SCHEMA.COLUMNS c
LEFT JOIN 
    INFORMATION_SCHEMA.KEY_COLUMN_USAGE kcu
    ON c.TABLE_SCHEMA = kcu.TABLE_SCHEMA 
       AND c.TABLE_NAME = kcu.TABLE_NAME 
       AND c.COLUMN_NAME = kcu.COLUMN_NAME
       AND kcu.CONSTRAINT_NAME IN (
           SELECT CONSTRAINT_NAME 
           FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS 
           WHERE CONSTRAINT_TYPE = 'PRIMARY KEY'
       )
WHERE 
    c.TABLE_NAME IN (
        SELECT TABLE_NAME 
        FROM INFORMATION_SCHEMA.TABLES 
        WHERE TABLE_TYPE = 'BASE TABLE'
    )
    AND c.TABLE_NAME NOT LIKE '__EF%';
GO

